
		<?php
		/* 
		 * phpMyAdmin Configuration File
		 * Generated by : phpMyAdmin v3.3.7 for Prestashop v1.6.0.9 by caparuni
		 * Date : October 27, 2014 - 7:13 pm
		*/
		
		$i = 0;
		$i++;
		$cfg['Servers'][$i]['host'] = 'localhost';
		$cfg['Servers'][$i]['user'] = 'tourc6ke_tourcz';
		$cfg['Servers'][$i]['password'] = 'T6Uk8QSm';
		$cfg['Servers'][$i]['only_db'] = 'tourc6ke_tourcz_db';
		
		$cfg['Servers'][$i]['extension'] = 'mysql';
		$cfg['Servers'][$i]['connect_type'] = 'tcp';
		$cfg['Servers'][$i]['compress'] = false;
		$cfg['Servers'][$i]['auth_type'] = 'config';
		$cfg['RightDisplayServers'] = false;
		$cfg['ShowServerInfo'] = false;
		?>
		<?php
		/* 
		 * phpMyAdmin Configuration File
		 * Generated by : phpMyAdmin v3.3.7 for Prestashop v1.6.1.6 by caparuni
		 * Date : September 25, 2018 - 3:25 pm
		*/
		
		$i = 0;
		$i++;
		$cfg['Servers'][$i]['host'] = 'localhost';
		$cfg['Servers'][$i]['user'] = 'spokojenymazlicek';
		$cfg['Servers'][$i]['password'] = 'I0A6rG0p4PuO8qVt';
		$cfg['Servers'][$i]['only_db'] = 'spokojenymazlicek';
		
		$cfg['Servers'][$i]['extension'] = 'mysql';
		$cfg['Servers'][$i]['connect_type'] = 'tcp';
		$cfg['Servers'][$i]['compress'] = false;
		$cfg['Servers'][$i]['auth_type'] = 'config';
		$cfg['RightDisplayServers'] = false;
		$cfg['ShowServerInfo'] = false;
		?>