<?php

class phpmyadmin extends Module
{	
	private $_html = '';
	private $_Errors = array();
	
	
 	function __construct()
 	{
 	 	$this->name = 'phpmyadmin';
 	 	$this->version = '3.3.7';
 	 	$this->tab = '[mod-id]';
		
		parent::__construct();
		
		$this->displayName = $this->l('phpMyAdmin');
		$this->description = $this->l('www.phpmyadmin.net');
		$config = $this->pmaConfigCheck();
	        if(empty($config))
	    		$this->warning = $this->l('Cannot write to \'/modules/'.$this->name.'/pma/\'. Please check folder permission ');
	                                        	
 	}

	function install()
	{
	 	if (!parent::install() )
	 		return false;
	 	self::pmaConfigCreate();
	 	return true;
	}
	
	public function uninstall()
	{
		if (!parent::uninstall() )
			return false;
		self::pmaConfigDelete();
		return true;
	}
	
	public function pmaConfigCheck()
	{
		if(!is_writable( $file = _PS_MODULE_DIR_.$this->name.'/pma/' )) 
			return false;
		return true;
	}
	
	public function pmaConfigCreate()
	{
		$file = _PS_MODULE_DIR_.$this->name.'/pma/config.inc.php';
		$conf ='
		<?php
		/* 
		 * '.$this->displayName.' Configuration File
		 * Generated by : '.$this->displayName.' v'.$this->version.' for Prestashop v'._PS_VERSION_.' by caparuni
		 * Date : '.date("F j, Y - g:i a").'
		*/
		
		$i = 0;
		$i++;
		$cfg[\'Servers\'][$i][\'host\'] = \''._DB_SERVER_.'\';
		$cfg[\'Servers\'][$i][\'user\'] = \''._DB_USER_.'\';
		$cfg[\'Servers\'][$i][\'password\'] = \''._DB_PASSWD_.'\';
		$cfg[\'Servers\'][$i][\'only_db\'] = \''._DB_NAME_.'\';
		
		$cfg[\'Servers\'][$i][\'extension\'] = \'mysql\';
		$cfg[\'Servers\'][$i][\'connect_type\'] = \'tcp\';
		$cfg[\'Servers\'][$i][\'compress\'] = false;
		$cfg[\'Servers\'][$i][\'auth_type\'] = \'config\';
		$cfg[\'RightDisplayServers\'] = false;
		$cfg[\'ShowServerInfo\'] = false;
		?>';
		
		$config = $this->pmaConfigCheck();
		if(empty($config)) $this->_Errors[] = 'Cannot write to '.$file;
		else 
		{
		    if (!$handle = fopen($file, 'a')) $this->_Errors[] = 'Cannot open file '.$file;
		    if (fwrite($handle, $conf) === FALSE) $this->_Errors[] = 'Cannot write to file '.$file;
		}
	}
	
	private function pmaConfigDelete()
	{
		$file = _PS_MODULE_DIR_.$this->name.'/pma/config.inc.php';
		unlink($file);
	}
	
	
	public function _displayForm()
	{
		$dir = __PS_BASE_URI__.'modules/'.$this->name.'/pma/db_structure.php?db='._DB_NAME_;
		$this->_html .= '
		<script type="text/javascript" src="'.__PS_BASE_URI__.'modules/'.$this->name.'/autoHeight.js"></script>
		<iframe src ="'.$dir.'" width="100%"  frameborder="0" scrolling="auto" class="autoHeight">
		    <p>Your browser does not support iframes.</p>
		</iframe>
		';
	}

	public function getContent()
	{
		$this->_html = '<h2>'.$this->displayName.'</h2>';
		if (!empty($this->_Errors)) 
		{
		    foreach ($this->_Errors AS $err)
			$this->_html .= '<div class="alert error">'. $err .'</div>';
			//$this->_html .= '<br><p><a href="javascript:history.back(1)" class="button">'.$this->l('back').'</a></p>';
		}
		else
		    $this->_displayForm();
		return $this->_html;
	}	




}
?>
